### ISSUE TITLE
Provide latest release as binary

### ISSUE THREAD

**Issue by cmichi** [paritytech/canvas-node#25]
## Problem

There should be an option to install `canvas-node` without compiling the entire project. In [this blog post](https://github.com/brson/rust-contract-comparison/blob/master/blog/parity-ink.md) regarding working with ink! it's mentioned that it took him 31 minutes to compile the project. That's definitely too long if somebody just wants to write a contract and test it.

## ToDo

- [ ] Talk to ops how they do this for Polkadot, we can probably take a similar pipeline.

- [ ] A `canvas-node` binary should be provided with the latest release.

- [ ] Update docs/tutorials so that they mention installing the binary as the first option.

**Comment by riusricardo** [comment]
This is a really good idea. It should also contain the spec file to connect to the testnet in case someone want to sync a full node.
It will be very helpful if we provide binaries for:
* Linux
* Mac OS
* Windows
